/*
  Codex dish illustrations, keyed by "<regionId>|<dish name>".

  Generated by scripts, not hand-written, and keyed on the region as well as
  the name because the codex carries the same dish twice: Dholl puri appears in
  both the Afro-Asia and the indenture volumes, and they are different cards.
  Deriving a filename from the name alone in TypeScript would silently collapse
  those two, so the mapping is explicit instead of clever.

  Like everything under public/media these are illustrations, not photographs.
  See data/media.ts and docs/DISCREPANCIES.md 15.
*/

const DISH_SLUGS: Record<string, string> = {
  "west|Akara": 'akara',
  "west|Red red": 'red-red',
  "west|Waakye": 'waakye',
  "west|Attiéké": 'atti-k',
  "west|Jollof rice": 'jollof-rice',
  "west|Egusi soup": 'egusi-soup',
  "west|Thieboudienne": 'thieboudienne',
  "east|Shiro wot": 'shiro-wot',
  "east|Misir wot": 'misir-wot',
  "east|Beyaynetu": 'beyaynetu',
  "east|Mchicha wa nazi": 'mchicha-wa-nazi',
  "east|Kachumbari": 'kachumbari',
  "east|Kisra with mullah": 'kisra-with-mullah',
  "east|Matoke": 'matoke',
  "north|Ful medames": 'ful-medames',
  "north|Koshari": 'koshari',
  "north|Lablabi": 'lablabi',
  "north|Zaalouk": 'zaalouk',
  "north|Bissara": 'bissara',
  "north|Couscous with seven vegetables": 'couscous-with-seven-vegetables',
  "north|Fatta": 'fatta',
  "central|Umngqusho": 'umngqusho',
  "central|Morogo / imifino": 'morogo-imifino',
  "central|Koki": 'koki',
  "central|Fumbwa": 'fumbwa',
  "central|Nsima or sadza with ndiwo": 'nsima-or-sadza-with-ndiwo',
  "central|Matapa": 'matapa',
  "central|Ndolé": 'ndol',
  "caribbean|Ital stew": 'ital-stew',
  "caribbean|Rice and peas": 'rice-and-peas',
  "caribbean|Callaloo": 'callaloo',
  "caribbean|Pikliz": 'pikliz',
  "caribbean|Cassava bread (ereba)": 'cassava-bread-ereba',
  "caribbean|Diri kole ak pwa": 'diri-kole-ak-pwa',
  "caribbean|Oil-down": 'oil-down',
  "afam|Okra soup": 'okra-soup',
  "afam|Benne wafers": 'benne-wafers',
  "afam|Texas caviar": 'texas-caviar',
  "afam|Hoppin’ John": 'hoppin-john',
  "afam|Red rice": 'red-rice',
  "afam|Maque choux": 'maque-choux',
  "afam|Potlikker greens": 'potlikker-greens',
  "afrosam|Farofa": 'farofa',
  "afrosam|Beiju & tapioca": 'beiju-tapioca',
  "afrosam|Enyucada": 'enyucada',
  "afrosam|Alegría": 'alegr-a',
  "afrosam|Tacu tacu": 'tacu-tacu',
  "afrosam|Patacones": 'patacones',
  "afrosam|Acarajé": 'acaraj',
  "afrosam|Moqueca": 'moqueca',
  "afroasia|Pilau": 'pilau',
  "afroasia|Dholl puri": 'dholl-puri',
  "afroasia|Rougail": 'rougail',
  "afroasia|Achar": 'achar',
  "afroasia|Cari (Creole curry)": 'cari-creole-curry',
  "afroasia|Chinese-Jamaican soy cooking": 'chinese-jamaican-soy-cooking',
  "afroasia|Mushroom adobo": 'mushroom-adobo',
  "indenture|Doubles": 'doubles',
  "indenture|Dholl puri": 'dholl-puri-2',
  "indenture|Dhalpuri roti": 'dhalpuri-roti',
  "indenture|Baigan choka": 'baigan-choka',
  "indenture|Seven curry": 'seven-curry',
  "indenture|Gateau piment": 'gateau-piment',
  "indenture|Pholourie & saheena": 'pholourie-saheena',
  "indenture|Bean-curry bunny chow": 'bean-curry-bunny-chow',
  "indenture|Pelau": 'pelau',
  "indenture|Kheer & gulab jamun": 'kheer-gulab-jamun',
  "italy|Pasta e ceci": 'pasta-e-ceci',
  "italy|Farinata": 'farinata',
  "italy|Panelle": 'panelle',
  "italy|Cuscusu trapanese": 'cuscusu-trapanese',
  "italy|Pizza marinara": 'pizza-marinara',
  "italy|Zighinì with injera": 'zighin-with-injera',
  "italy|Baasto with tomato & cardamom": 'baasto-with-tomato-cardamom',
  "italy|Eritrean-style lasagna": 'eritrean-style-lasagna',
  "italy|Teff polenta with mushroom ragù": 'teff-polenta-with-mushroom-rag',
  "italy|Fonio risotto": 'fonio-risotto',
  "italy|Collard pesto pasta": 'collard-pesto-pasta',
};

/* Returns the image path, or null when the codex has no illustration for a dish. */
export function dishImage(regionId: string, name: string): string | null {
  const slug = DISH_SLUGS[regionId + '|' + name];
  return slug ? '/media/dish-' + slug + '.webp' : null;
}

export const DISH_COUNT = 78;
